"""
MQTT client for grain sampling robot cloud communication.

Provides a thread-safe MQTT client with:
- JSON serialization/deserialization for dict payloads
- Auto-reconnect with exponential backoff
- Outgoing message queue for thread-safe publishing
- Signal/event callbacks for connect, disconnect, and message events
"""

import json
import logging
import queue
import re
import threading
import time
from dataclasses import dataclass, field
from typing import Any, Callable, Dict, List, Optional

import paho.mqtt.client as mqtt
from paho.mqtt.enums import CallbackAPIVersion

logger = logging.getLogger(__name__)


def parse_broker_url(url: str) -> tuple:
    """Parse an MQTT broker URL into (host, port).

    Args:
        url: Broker URL in format ``mqtt://host:port`` (port defaults to 1883).

    Returns:
        Tuple of (host, port).

    Raises:
        ValueError: If the URL format is invalid.
    """
    match = re.match(r"^mqtt://([^:/\s]+)(?::(\d+))?/?$", url)
    if not match:
        raise ValueError(
            f"Invalid broker URL: {url!r}. Expected format: mqtt://host:port"
        )
    host = match.group(1)
    port = int(match.group(2)) if match.group(2) else 1883
    return host, port


@dataclass
class OutgoingMessage:
    """A message queued for publishing to the MQTT broker."""

    topic: str
    payload: Dict[str, Any]
    qos: int = 1
    retain: bool = False


@dataclass
class ReceivedMessage:
    """A message received from the MQTT broker, already deserialized."""

    topic: str
    payload: Dict[str, Any]
    timestamp: float = field(default_factory=time.time)


class MQTTClient:
    """Thread-safe MQTT client with JSON serialization and auto-reconnect.

    Features:
        - JSON serialization/deserialization for ``dict`` payloads
        - Thread-safe publish via an internal ``queue.Queue``
        - Auto-reconnect with exponential backoff (1s, 2s, 4s, … max 60s)
        - Signal/event callbacks: ``on_connect``, ``on_disconnect``, ``on_message``

    Configuration via ``config`` dict (or environment):
        - ``broker_url`` (default: ``mqtt://cloud-test.client.com:1883``)
        - ``client_id`` (default: auto-generated by paho)
        - ``keepalive`` (default: 60 seconds)
        - ``reconnect_min_delay`` (default: 1 second)
        - ``reconnect_max_delay`` (default: 60 seconds)
    """

    DEFAULT_BROKER_URL = "mqtt://cloud-test.client.com:1883"

    def __init__(self, config: Optional[Dict[str, Any]] = None) -> None:
        self._config = config or {}
        self._parse_config()

        # Connection state
        self._connected = threading.Event()
        self._disconnect_requested = threading.Event()
        self._reconnect_attempt = 0

        # Outgoing message queue (thread-safe)
        self._outbox: queue.Queue = queue.Queue()

        # Registered subscriptions: {topic: [callback, ...]}
        self._subscriptions: Dict[str, List[Callable]] = {}

        # Topic-level callbacks from subscribe()
        self._topic_callbacks: List[tuple] = []

        # Signal event callbacks
        self._on_connect_callbacks: List[Callable] = []
        self._on_disconnect_callbacks: List[Callable] = []
        self._on_message_callbacks: List[Callable] = []

        # Create paho-mqtt client
        self._client = mqtt.Client(
            CallbackAPIVersion.VERSION2,
            client_id=self._client_id if self._client_id else None,
        )
        self._client.on_connect = self._on_paho_connect
        self._client.on_disconnect = self._on_paho_disconnect
        self._client.on_message = self._on_paho_message

        # Threading: publisher worker + reconnector worker
        self._publisher_thread: Optional[threading.Thread] = None
        self._reconnector_thread: Optional[threading.Thread] = None
        self._running = threading.Event()

    # ------------------------------------------------------------------
    # Configuration parsing
    # ------------------------------------------------------------------

    def _parse_config(self) -> None:
        broker_url = self._config.get("broker_url", self.DEFAULT_BROKER_URL)
        self._host, self._port = parse_broker_url(broker_url)
        self._client_id = self._config.get("client_id", "")
        self._keepalive = int(self._config.get("keepalive", 60))
        self._reconnect_min_delay = float(
            self._config.get("reconnect_min_delay", 1.0)
        )
        self._reconnect_max_delay = float(
            self._config.get("reconnect_max_delay", 60.0)
        )

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def connect(
        self,
        host: Optional[str] = None,
        port: Optional[int] = None,
        client_id: Optional[str] = None,
        keepalive: Optional[int] = None,
    ) -> None:
        """Connect to the MQTT broker.

        Args:
            host: Broker hostname (overrides config).
            port: Broker port (overrides config).
            client_id: MQTT client ID (overrides config).
            keepalive: Keepalive interval in seconds (overrides config).
        """
        if host is not None:
            self._host = host
        if port is not None:
            self._port = port
        if client_id is not None:
            self._client_id = client_id
            # Re-create client with new ID if not connected yet
            if not self._client.is_connected():
                self._client = mqtt.Client(
                    CallbackAPIVersion.VERSION2,
                    client_id=self._client_id if self._client_id else None,
                )
                self._client.on_connect = self._on_paho_connect
                self._client.on_disconnect = self._on_paho_disconnect
                self._client.on_message = self._on_paho_message
        if keepalive is not None:
            self._keepalive = keepalive

        self._disconnect_requested.clear()
        self._running.set()

        logger.info(
            "Connecting to broker %s:%s (client_id=%s, keepalive=%s)",
            self._host, self._port, self._client_id, self._keepalive,
        )

        try:
            self._client.connect(self._host, self._port, self._keepalive)
            self._client.loop_start()
        except Exception as exc:
            logger.error("Failed to connect: %s", exc)
            raise

        # Start publisher worker thread
        if self._publisher_thread is None or not self._publisher_thread.is_alive():
            self._publisher_thread = threading.Thread(
                target=self._publisher_loop, daemon=True, name="mqtt-publisher"
            )
            self._publisher_thread.start()

        # Start reconnector worker thread
        if self._reconnector_thread is None or not self._reconnector_thread.is_alive():
            self._reconnector_thread = threading.Thread(
                target=self._reconnector_loop, daemon=True, name="mqtt-reconnector"
            )
            self._reconnector_thread.start()

    def disconnect(self) -> None:
        """Disconnect from the MQTT broker."""
        self._disconnect_requested.set()
        self._running.clear()
        self._connected.clear()
        try:
            self._client.loop_stop()
            self._client.disconnect()
        except Exception as exc:
            logger.debug("Error during disconnect: %s", exc)
        logger.info("Disconnected from broker")

    def publish(
        self,
        topic: str,
        payload_dict: Dict[str, Any],
        qos: int = 1,
        retain: bool = False,
    ) -> None:
        """Publish a dictionary payload to the given topic (thread-safe).

        The payload is serialized to JSON and queued for asynchronous
        publishing on the internal worker thread.

        Args:
            topic: MQTT topic to publish to.
            payload_dict: Dictionary payload (will be JSON-serialized).
            qos: Quality of Service level (0, 1, or 2).
            retain: Whether the message should be retained by the broker.
        """
        msg = OutgoingMessage(topic=topic, payload=payload_dict, qos=qos, retain=retain)
        self._outbox.put_nowait(msg)

    def subscribe(
        self, topic: str, callback: Callable[[Dict[str, Any]], None]
    ) -> None:
        """Subscribe to a topic with a JSON-deserializing callback.

        The callback receives the deserialized ``dict`` payload when a
        message arrives on the subscribed topic.

        Args:
            topic: MQTT topic filter (may include wildcards).
            callback: Callable accepting a single ``dict`` argument.
        """
        if topic not in self._subscriptions:
            self._subscriptions[topic] = []
            self._client.subscribe(topic)
        self._subscriptions[topic].append(callback)

    def unsubscribe(self, topic: str) -> None:
        """Unsubscribe from a topic and remove all its callbacks.

        Args:
            topic: MQTT topic to unsubscribe from.
        """
        self._subscriptions.pop(topic, None)
        self._client.unsubscribe(topic)

    def is_connected(self) -> bool:
        """Return whether the client is currently connected to the broker."""
        return self._connected.is_set()

    # ------------------------------------------------------------------
    # Signal registration
    # ------------------------------------------------------------------

    def on_connect(self, callback: Callable) -> None:
        """Register a callback for the ``on_connect`` event.

        The callback receives no arguments.
        """
        self._on_connect_callbacks.append(callback)

    def on_disconnect(self, callback: Callable) -> None:
        """Register a callback for the ``on_disconnect`` event.

        The callback receives no arguments.
        """
        self._on_disconnect_callbacks.append(callback)

    def on_message(self, callback: Callable) -> None:
        """Register a callback for the ``on_message`` event.

        The callback receives a ``ReceivedMessage`` instance.
        """
        self._on_message_callbacks.append(callback)

    # ------------------------------------------------------------------
    # Paho callback handlers
    # ------------------------------------------------------------------

    def _on_paho_connect(
        self,
        client: mqtt.Client,
        userdata: Any,
        flags: Dict[str, Any],
        reason_code: Any,
        properties: Any = None,
    ) -> None:
        """Internal: paho connection callback."""
        if reason_code == 0:
            logger.info("Connected to broker successfully")
            self._connected.set()
            self._reconnect_attempt = 0
            # Re-subscribe to all registered topics
            for topic in self._subscriptions:
                client.subscribe(topic)
            # Fire on_connect signals
            for cb in self._on_connect_callbacks:
                try:
                    cb()
                except Exception as exc:
                    logger.error("on_connect callback error: %s", exc)
        else:
            logger.warning("Connection failed with reason_code=%s", reason_code)

    def _on_paho_disconnect(
        self,
        client: mqtt.Client,
        userdata: Any,
        reason_code: Any,
        properties: Any = None,
    ) -> None:
        """Internal: paho disconnection callback."""
        self._connected.clear()
        if not self._disconnect_requested.is_set():
            logger.warning(
                "Unexpected disconnect (reason_code=%s), will attempt reconnection",
                reason_code,
            )
        else:
            logger.info("Disconnected from broker (reason_code=%s)", reason_code)
        # Fire on_disconnect signals
        for cb in self._on_disconnect_callbacks:
            try:
                cb()
            except Exception as exc:
                logger.error("on_disconnect callback error: %s", exc)

    def _on_paho_message(
        self,
        client: mqtt.Client,
        userdata: Any,
        message: mqtt.MQTTMessage,
    ) -> None:
        """Internal: paho message callback."""
        try:
            payload = json.loads(message.payload.decode("utf-8"))
        except (json.JSONDecodeError, UnicodeDecodeError) as exc:
            logger.warning(
                "Failed to deserialize message on %s: %s",
                message.topic, exc,
            )
            return

        received = ReceivedMessage(
            topic=message.topic, payload=payload, timestamp=time.time()
        )

        # Dispatch to topic-level callbacks
        for topic_filter, callbacks in self._subscriptions.items():
            if mqtt.topic_matches_sub(topic_filter, message.topic):
                for cb in callbacks:
                    try:
                        cb(payload)
                    except Exception as exc:
                        logger.error(
                            "Topic callback error on %s: %s", message.topic, exc
                        )

        # Fire general on_message signals
        for cb in self._on_message_callbacks:
            try:
                cb(received)
            except Exception as exc:
                logger.error("on_message callback error: %s", exc)

    # ------------------------------------------------------------------
    # Internal worker loops
    # ------------------------------------------------------------------

    def _publisher_loop(self) -> None:
        """Worker thread: consumes the outgoing message queue and publishes."""
        while self._running.is_set():
            try:
                msg: OutgoingMessage = self._outbox.get(timeout=1.0)
            except queue.Empty:
                continue

            if not self._connected.is_set():
                logger.debug("Not connected, requeueing message on %s", msg.topic)
                self._outbox.put(msg)
                time.sleep(1.0)
                continue

            try:
                payload_str = json.dumps(msg.payload, ensure_ascii=False)
                info = self._client.publish(
                    msg.topic, payload_str, qos=msg.qos, retain=msg.retain
                )
                if info.rc == mqtt.MQTT_ERR_SUCCESS:
                    logger.debug(
                        "Published to %s (mid=%s)", msg.topic, info.mid
                    )
                else:
                    logger.warning(
                        "Publish to %s failed (rc=%s), requeueing",
                        msg.topic, info.rc,
                    )
                    self._outbox.put(msg)
            except Exception as exc:
                logger.error("Publish error on %s: %s", msg.topic, exc)
                self._outbox.put(msg)
                time.sleep(1.0)

    def _reconnector_loop(self) -> None:
        """Worker thread: monitors connection and reconnects with backoff."""
        while self._running.is_set():
            if not self._connected.is_set() and not self._disconnect_requested.is_set():
                self._reconnect_attempt += 1
                delay = min(
                    self._reconnect_min_delay
                    * (2 ** (self._reconnect_attempt - 1)),
                    self._reconnect_max_delay,
                )
                logger.info(
                    "Reconnecting in %.1f seconds (attempt #%d)",
                    delay, self._reconnect_attempt,
                )
                self._running.wait(delay)
                if not self._running.is_set():
                    break
                try:
                    logger.info(
                        "Reconnect attempt #%d to %s:%s",
                        self._reconnect_attempt, self._host, self._port,
                    )
                    self._client.reconnect()
                except Exception as exc:
                    logger.warning(
                        "Reconnect attempt #%d failed: %s",
                        self._reconnect_attempt, exc,
                    )
            else:
                self._running.wait(2.0)

    # ------------------------------------------------------------------
    # Context manager support
    # ------------------------------------------------------------------

    def __enter__(self) -> "MQTTClient":
        return self

    def __exit__(self, *args: Any) -> None:
        self.disconnect()
